"""Add order table

Revision ID: 46ebf14d43e1
Revises: ef27446a5c57
Create Date: 2019-04-20 17:43:02.008541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ebf14d43e1'
down_revision = 'ef27446a5c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon', sa.String(length=20), nullable=True),
    sa.Column('total_bill', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_orders_event_id_events')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_orders_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
