"""add more feature to events table

Revision ID: b86e6526fc48
Revises: 503cb9d5dcc1
Create Date: 2019-04-18 19:05:17.363366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86e6526fc48'
down_revision = '503cb9d5dcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('events', sa.Column(
        'description', sa.Text()))
    op.add_column('events', sa.Column('image_url', sa.Text()))
    op.add_column('events', sa.Column('price', sa.Integer()))
    op.add_column('events', sa.Column('address', sa.Text()))
    op.add_column('events', sa.Column('time', sa.Time()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'description')
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'price')
    op.drop_column('events', 'address')
    op.drop_column('events', 'time')
    # ### end Alembic commands ###
